#include "callback.h"
#include "tibrv.h"

// _cgo_export.h is auto-generated by Go
#include "_cgo_export.h"

void c_to_go_callback(tibrvEvent event, tibrvMsg message, void* closure) {
    Go_callback(event, message, closure)
}